<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IsolationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsolationRepository extends EntityRepository
{
}
