<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('position' => 'ASC'));
    }
}
