doctrine: 
  dbal: 
    charset: UTF8
    dbname: "%database_name%"
    driver: pdo_mysql
    host: "%database_host%"
    password: "%database_password%"
    port: "%database_port%"
    user: "%database_user%"
  orm: 
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore

framework: 
  csrf_protection: ~
  default_locale: "%locale%"
  form: ~
  fragments: ~
  http_method_override: true
  router: 
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  session: 
    handler_id: ~
  templating: 
    engines: 
      - twig
  translator: ~
  trusted_hosts: ~
  trusted_proxies: ~
  validation: 
    enable_annotations: true

imports: 
  - 
    resource: parameters.yml
  - 
    resource: security.yml
  - 
    resource: services.yml

parameters: 
  locale: fr
  app.path.images_article: /uploads/images/article

swiftmailer: 
  host: "%mailer_host%"
  password: "%mailer_password%"
  spool: 
    type: memory
  transport: "%mailer_transport%"
  username: "%mailer_user%"

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User

easy_admin:
  entities:
    Users:
      class: AppBundle\Entity\User
      edit:
        fields:
          - roles
          - password
          - username
          - email
          - enabled
      list:
        fields:
          - id
          - username
          - email
          - roles
      new:
        fields:
          - roles
          - plainPassword
          - username
          - email
          - enabled
    Article:
      class: AppBundle\Entity\Article
      list:
        fields:
          - { property: 'image', type: 'image', base_path: %app.path.images_article% }
      show:
        fields:
          - { property: 'image', type: 'image', base_path: %app.path.images_article% }
      form:
        fields:
          - { property: 'imageFile', type: 'vich_image' }
    Event:
      class: AppBundle\Entity\Event
    Service:
      class: AppBundle\Entity\Service
    Volontary:
      class: AppBundle\Entity\Volontary
assetic:
    debug:       "%kernel.debug%"
    bundles:    [AppBundle]
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

vich_uploader:
    db_driver: orm
    mappings:
        images_article:
            uri_prefix:         %app.path.images_article%
            upload_destination: %kernel.root_dir%/../web/uploads/images/article