doctrine: 
  dbal: 
    charset: UTF8
    dbname: "%database_name%"
    driver: pdo_mysql
    host: "%database_host%"
    password: "%database_password%"
    port: "%database_port%"
    user: "%database_user%"
  orm: 
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore

easy_admin: 
  entities:
    Config: 
      class: AppBundle\Entity\Config
    Currently: 
      class: AppBundle\Entity\Currently
    Escape: 
      class: AppBundle\Entity\Escape
    Isolation:
      class: AppBundle\Entity\Isolation
    Users:
      class: AppBundle\Entity\User
      edit: 
        fields: 
          - roles
          - password
          - username
          - email
          - enabled
      list: 
        fields: 
          - id
          - username
          - email
          - roles
      new: 
        fields: 
          - roles
          - plainPassword
          - username
          - email
          - enabled

fos_user: 
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User

framework: 
  csrf_protection: ~
  default_locale: "%locale%"
  form: ~
  fragments: ~
  http_method_override: true
  router: 
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  session: 
    handler_id: ~
  templating: 
    engines: 
      - twig
  translator: ~
  trusted_hosts: ~
  trusted_proxies: ~
  validation: 
    enable_annotations: true

imports: 
  - 
    resource: parameters.yml
  - 
    resource: security.yml
  - 
    resource: services.yml

parameters: 
  locale: fr

swiftmailer: 
  host: "%mailer_host%"
  password: "%mailer_password%"
  spool: 
    type: memory
  transport: "%mailer_transport%"
  username: "%mailer_user%"

twig: 
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
