doctrine: 
  dbal: 
    charset: UTF8
    dbname: "%database_name%"
    driver: pdo_mysql
    host: "%database_host%"
    password: "%database_password%"
    port: "%database_port%"
    user: "%database_user%"
  orm: 
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore

framework: 
  csrf_protection: ~
  default_locale: "%locale%"
  form: ~
  fragments: ~
  http_method_override: true
  router: 
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  session: 
    handler_id: ~
  templating: 
    engines: 
      - twig        
  translator: ~
  trusted_hosts: ~
  trusted_proxies: ~
  validation: 
    enable_annotations: true
  assets:
    packages:
            img:
                base_path: /assets/imgs/
            pdf:
                base_path: %app.path.pdf_files%
            img_article:
                base_path: %app.path.images_article%
            img_icon:
                base_path: %app.path.images_icon%
            img_event:
                base_path: %app.path.images_event%
            img_service:
                base_path: %app.path.images_service%
            img_partner:
                base_path: %app.path.images_article%

twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

imports: 
  - 
    resource: parameters.yml
  - 
    resource: security.yml
  - 
    resource: services.yml

parameters: 
  locale: fr
  app.path.images_article: /assets/imgs/article
  app.path.images_icon: /assets/imgs/icons
  app.path.images_event: /assets/imgs/event
  app.path.images_service: /assets/imgs/service
  app.path.images_partner: /assets/partenaires
  app.path.pdf_files: /assets/pdf

swiftmailer: 
  host: "%mailer_host%"
  password: "%mailer_password%"
  spool: 
    type: memory
  transport: "%mailer_transport%"
  username: "%mailer_user%"

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User

assetic:
    debug:       "%kernel.debug%"
    bundles:    [AppBundle]
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'


vich_uploader:
    db_driver: orm
    mappings:
        images_article:
            uri_prefix:         %app.path.images_article%
            upload_destination: %kernel.root_dir%/../web/assets/imgs/article
            namer: vich_uploader.namer_uniqid
        images_icon:
            uri_prefix:         %app.path.images_icon%
            upload_destination: %kernel.root_dir%/../web/assets/icons
            namer: vich_uploader.namer_uniqid
        images_event:
            uri_prefix:         %app.path.images_event%
            upload_destination: %kernel.root_dir%/../web/assets/imgs/event
            namer: vich_uploader.namer_uniqid
        images_service:
            uri_prefix:         %app.path.images_service%
            upload_destination: %kernel.root_dir%/../web/assets/imgs/service
            namer: vich_uploader.namer_uniqid
        images_partner:
            uri_prefix:         %app.path.images_partner%
            upload_destination: %kernel.root_dir%/../web/assets/partenaires
            namer: vich_uploader.namer_uniqid
        pdf_files:
            uri_prefix: %app.path.pdf_files%
            upload_destination: %kernel.root_dir%/../web/assets/pdf
            namer: vich_uploader.namer_uniqid
