doctrine: 
  dbal: 
    charset: UTF8
    dbname: "%database_name%"
    driver: pdo_mysql
    host: "%database_host%"
    password: "%database_password%"
    port: "%database_port%"
    user: "%database_user%"
  orm: 
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore

framework: 
  csrf_protection: ~
  default_locale: "%locale%"
  form: ~
  fragments: ~
  http_method_override: true
  router: 
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  session: 
    handler_id: ~
  templating: 
    engines: 
      - twig
  translator: ~
  trusted_hosts: ~
  trusted_proxies: ~
  validation: 
    enable_annotations: true

imports: 
  - 
    resource: parameters.yml
  - 
    resource: security.yml
  - 
    resource: services.yml

parameters: 
  locale: fr
  app.path.images_article: /uploads/images/article
  app.path.images_event: /uploads/images/event
  app.path.images_service: /uploads/images/service
  app.path.pdf_files: /uploads/files/pdf

swiftmailer: 
  host: "%mailer_host%"
  password: "%mailer_password%"
  spool: 
    type: memory
  transport: "%mailer_transport%"
  username: "%mailer_user%"

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User

easy_admin:
  entities:
    Users:
      class: AppBundle\Entity\User
      edit:
        fields:
          - roles
          - password
          - username
          - email
          - enabled
          - { property: 'pdf', template: 'pdf_back', base_path: %app.path.pdf_files% }
      list:
        fields:
          - id
          - username
          - email
          - roles
          - pdf
      new:
        fields:
          - roles
          - plainPassword
          - username
          - email
          - enabled
          - { property: 'pdf', template: 'pdf_back', base_path: %app.path.pdf_files% }
    Article:
      class: AppBundle\Entity\Article
      list:
        fields:
          - title
          - content
          - position
          - { property: 'image', type: 'image', base_path: %app.path.images_article% }
          - pdf
      show:
        fields:
          - title
          - content
          - position
          - { property: 'image', type: 'image', base_path: %app.path.images_article% }
          - pdf
      form:
        fields:
          - title
          - content
          - position
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'pdf', template: 'pdf_back', base_path: %app.path.pdf_files% }

    Event:
      class: AppBundle\Entity\Event
      list:
        fields:
          - name
          - shortDesc
          - body
          - { property: 'thumbnail', type: 'image', base_path: %app.path.images_event% }
          - date
          - inscription
          - flickr
          - youtube
          - { property: 'image1', type: 'image', base_path: %app.path.images_event% }
          - { property: 'image2', type: 'image', base_path: %app.path.images_event% }
          - { property: 'image3', type: 'image', base_path: %app.path.images_event% }
          - pdf
      show:
        fields:
          - name
          - shortDesc
          - body
          - { property: 'thumbnail', type: 'image', base_path: %app.path.images_event% }
          - date
          - inscription
          - flickr
          - youtube
          - { property: 'image1', type: 'image', base_path: %app.path.images_event% }
          - { property: 'image2', type: 'image', base_path: %app.path.images_event% }
          - { property: 'image3', type: 'image', base_path: %app.path.images_event% }
          - pdf
      form:
        fields:
          - name
          - shortDesc
          - body
          - { property: 'thumbnailFile', type: 'vich_image' }
          - date
          - inscription
          - flickr
          - youtube
          - { property: 'imageFile1', type: 'vich_image' }
          - { property: 'imageFile2', type: 'vich_image' }
          - { property: 'imageFile3', type: 'vich_image' }
          - { property: 'pdf', template: 'pdf_back', base_path: %app.path.pdf_files% }
    Service:
      class: AppBundle\Entity\Service
    Pdf:
      class: AppBundle\Entity\Pdf
      list:
        fields:
          - name
          - { property: 'color', label: 'Couleur' }
          - location
          - position
          - { property: 'pdf', template: 'pdf_back', base_path: %app.path.pdf_files% }
      show:
        fields:
          - name
          - color
          - location
          - position
          - { property: 'pdf', template: 'pdf_back', base_path: %app.path.pdf_files% }
      form:
        fields:
          - name
          - { property: 'color', type: 'color_choice', label: 'Couleur' }
          - location
          - position
          - { property: 'pdfFile', type: 'vich_file' }
assetic:
    debug:       "%kernel.debug%"
    bundles:    [AppBundle]
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

vich_uploader:
    db_driver: orm
    mappings:
        images_article:
            uri_prefix:         %app.path.images_article%
            upload_destination: %kernel.root_dir%/../web/uploads/images/article
        images_event:
            uri_prefix:         %app.path.images_event%
            upload_destination: %kernel.root_dir%/../web/uploads/images/event
        images_service:
            uri_prefix:         %app.path.images_service%
            upload_destination: %kernel.root_dir%/../web/uploads/images/service
        pdf_files:
            uri_prefix: %app.path.pdf_files%
            upload_destination: %kernel.root_dir%/../web/uploads/files/pdf